# Generated by Django 2.2.6 on 2019-10-19 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=1)),
                ('born', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=35)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Work')),
            ],
        ),
    ]
